name: My_Workflow_1

on:
    push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: checkout Repo
              uses: action/checkout@v4
            - name: welcome Message
              run: echo "welcome to My Github Action tutorial"
            - name: list files
              run: ls