name: JAVA_INSTALLATION

on:
  push:
    branches: [ main ]
jobs:
  setup-java:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # Options: temurin, zulu, adopt, etc.
          java-version: '17'

      - name: Verify Java installation
        run: java -version
